name: bmcmanager
version: git
summary: bmcmanager
description: BMCManager tool
base: core20
confinement: strict
grade: stable
license: GPL-3.0
architectures:
  - build-on: amd64
  - build-on: arm64

parts:
  bmcmanager:
    plugin: python
    #python-version: python3
    source: .
    override-build: |
      set -eox
      if [ "x$SNAPCRAFT_PROJECT_VERSION" != "xgit" ]; then
        export PBR_VERSION=$SNAPCRAFT_PROJECT_VERSION
      fi
      snapcraftctl build
    stage-packages:
      - freeipmi
      - ipmitool
  completer:
    plugin: nil
    override-prime: bmcmanager complete > bmcmanager-autocomplete.bash
  wrapper:
    plugin: dump
    source: ./scripts/
    organize:
      scripts/bmcmanager.wrapper: usr/bin/bmcmanager.wrapper

apps:
  bmcmanager:
    command: bmcmanager.wrapper
    plugs: [home, network]
    completer: bmcmanager-autocomplete.bash
  ipmitool:
    command: usr/bin/ipmitool
    plugs: [network]
  ipmi-sensors:
    command: usr/sbin/ipmi-sensors
    plugs: [network]
  ipmi-sel:
    command: usr/sbin/ipmi-sel
    plugs: [network]
  ipmi-dcmi:
    command: usr/sbin/ipmi-dcmi
    plugs: [network]
