name: Python Code

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v1
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install tox
      - name: Lint python code
        run: tox -e lint
      - name: Test binaries
        run: tox -e testbinary
      - name: Test packages
        run: tox -e testpackages
