name: Python Code

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v1
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install tox twine wheel
      - name: Test with tox
        run: tox
      - name: Build packages
        run: python setup.py sdist bdist_wheel
        env:
          BMCMANAGER_IGNORE_MISSING_BINARIES: 1
      - name: Check packages
        run: twine check dist/*
