name: Development Docker Image

on:
  push:
    branches: [master]

jobs:
  build:
    name: Release Development Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Retrieve build information
        run: |
          echo "COMMIT=${GITHUB_SHA::8}" >> $GITHUB_ENV
          echo "VERSION=$(sh scripts/version.sh)" >> $GITHUB_ENV
          echo "RUNID=${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: cloudeng
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            cloudeng/bmcmanager:${{ env.VERSION }}-dev-${{ env.RUNID }}-${{ env.COMMIT }}
            cloudeng/bmcmanager:latest-dev
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
