name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'

jobs:
  build:
    name: Release bmcmanager
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Retrieve build information
        run: |
          echo "::set-env name=VERSION::${GITHUB_REF#refs/tags/}"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: cloudeng
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            cloudeng/bmcmanager:${{ env.VERSION }}
            cloudeng/bmcmanager:latest
      - name: Docker Image Digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install tox twine wheel
      - name: Test with tox
        run: tox
      - name: Build packages
        run: python setup.py sdist bdist_wheel
        env:
          BMCMANAGER_IGNORE_MISSING_BINARIES: 1
      - name: Check packages
        run: twine check dist/*
      - name: Publish on PyPI
        run: twine upload dist/* -u __token__ -p "${{ secrets.PYPI_TOKEN }}"
