name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'

jobs:
  build:
    name: Release bmcmanager
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Retrieve build information
        run: |
          echo "::set-env name=VERSION::$(sh scripts/version.sh)"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: cloudeng
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            cloudeng/bmcmanager:${{ env.VERSION }}
            cloudeng/bmcmanager:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      - name: Build python packages
        run: python setup.py bdist_wheel sdist
        env:
          BMCMANAGER_IGNORE_MISSING_BINARIES: 1
      - name: Publish on PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
