name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'

jobs:
  build:
    name: Release bmcmanager
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Retrieve build information
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: cloudeng
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            cloudeng/bmcmanager:${{ env.VERSION }}
            cloudeng/bmcmanager:latest
      - name: Docker Image Digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install tox
        run: |
          python -m pip install -U pip
          pip install tox
      - name: Build and check packages
        run: tox -e testpackages
      - name: Publish on PyPI
        run: tox -e publish -- -u __token__ -p "${{ secrets.PYPI_TOKEN }}"
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ env.VERSION }}
          draft: true
          prerelease: ${{ contains(env.VERSION, 'rc') }}
          body: |
            BMCManager ${{ env.VERSION }}

            ## Pip

            - `pip install bmcmanager`

            ## Snap

            - `sudo snap install bmcmanager`

            ## Docker Images

            - `docker pull cloudeng/bmcmanager:${{ env.VERSION }}`
