name: Snapcraft Build

on: [pull_request]

jobs:
  test:
    name: Test Snap Build
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v1
      - name: Install Snapcraft with LXD
        uses: samuelmeuli/action-snapcraft@v1
        with:
          use_lxd: true
      - name: Build snap
        run: sg lxd -c 'snapcraft --use-lxd'
